### PR TITLE
Task 1 completed

### PR DESCRIPTION
**Pull request by RishikaAg17**
Issue: 1

### CODE REVIEW

**Review by GammaMicrowave — CHANGES_REQUESTED** [review]
host your website on github pages. You can watch the reference video on discord in the resources channel.

**Comment by RishikaAg17** [comment]
@GammaMicrowave sir changes updated. Kindly merge the pr.

**Review by GammaMicrowave — CHANGES_REQUESTED** [review]
add the link of the repo instead of hosting link just change it to this link
https://github.com/RishikaAg17/WEBDEV

**Comment by RishikaAg17** [comment]
@GammaMicrowave Sir link updated. Kindly check and merge the PR.

**Pull request merged**
